-- MySQL Script generated by MySQL Workbench
-- 05/26/17 11:43:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jgsc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jgsc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jgsc` DEFAULT CHARACTER SET utf8 ;
USE `jgsc` ;

-- -----------------------------------------------------
-- Table `jgsc`.`consultant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`consultant` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `user_name` VARCHAR(128) NULL COMMENT '用户名',
  `head_img` VARCHAR(512) NULL COMMENT '头像地址',
  `phone` VARCHAR(11) NULL COMMENT '电话',
  `wx_count` VARCHAR(128) NULL COMMENT '微信号',
  `ability_point` INT NULL DEFAULT 5 COMMENT '能力得分，默认5',
  `attitude_point` INT NULL DEFAULT 5 COMMENT '态度分,默认5',
  `status` INT NULL DEFAULT 1 COMMENT '状态，默认1表示正常，2表示异常',
  PRIMARY KEY (`id`))
COMMENT = '顾问表';


-- -----------------------------------------------------
-- Table `jgsc`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `uuid` VARCHAR(32) NULL,
  `user_name` VARCHAR(128) NULL COMMENT '用户名',
  `password` VARCHAR(45) NULL COMMENT '密码',
  `head_img` VARCHAR(256) NULL,
  `phone` VARCHAR(45) NULL COMMENT '手机',
  `wx_openid` VARCHAR(128) NULL COMMENT '微信openid',
  `qq_openid` VARCHAR(128) NULL COMMENT 'QQ openid',
  `face_openid` VARCHAR(128) NULL COMMENT 'facebook openid',
  `user_type` INT NULL DEFAULT 1 COMMENT '用户类型，默认1表示仅买家，2表示买家卖家互通，3表示管理员',
  `admin_type` INT NULL DEFAULT 1 COMMENT '管理员类别，默认1表示系统管理员',
  `bull_level` INT NULL DEFAULT 1 COMMENT '买家等级，默认1',
  `seller_level` INT NULL DEFAULT 1 COMMENT '卖家等级，默认1',
  `auth_status` INT NULL DEFAULT 0 COMMENT '认证状态，默认0表示未认证，1表示认证中，2表示认真成功，3表示认证失败',
  `token` VARCHAR(256) NULL,
  `consultant_id` BIGINT(20) NOT NULL COMMENT '顾问id',
  `is_member` INT NULL DEFAULT 0 COMMENT '是否会员，默认0不是会员，1表示会员',
  `member_time` DATE NULL COMMENT '会员有效期',
  `status` INT NULL DEFAULT 1 COMMENT '默认1表示正常，2表示封号，3表示删除',
  PRIMARY KEY (`id`),
  INDEX `fk_user_consultant1_idx` (`consultant_id` ASC),
  CONSTRAINT `fk_user_consultant1`
    FOREIGN KEY (`consultant_id`)
    REFERENCES `jgsc`.`consultant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '用户基本信息表';


-- -----------------------------------------------------
-- Table `jgsc`.`sort_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`sort_type` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `sort_name` VARCHAR(128) NULL COMMENT '类名',
  `one_type_id` BIGINT(20) NULL COMMENT '一级目录',
  `two_type_id` BIGINT(20) NULL COMMENT '二级目录（备用）',
  `status` INT NULL DEFAULT 1 COMMENT '默认1表示正常，2表示弃用',
  PRIMARY KEY (`id`))
COMMENT = '类别表';


-- -----------------------------------------------------
-- Table `jgsc`.`trade_area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`trade_area` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `area_name` VARCHAR(128) NULL COMMENT '商圈名',
  `area_code` VARCHAR(45) NULL COMMENT '区域代码，可不填',
  `status` INT NULL DEFAULT 1 COMMENT '状态，默认1表示正常，2表示关闭',
  PRIMARY KEY (`id`))
COMMENT = '商圈';


-- -----------------------------------------------------
-- Table `jgsc`.`shop_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`shop_info` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `user_id` BIGINT(20) NOT NULL COMMENT '卖家id',
  `seller_type` INT NULL COMMENT '卖家类型：1表示实体店，2表示工厂店，3表示网批店',
  `head_img` VARCHAR(512) NULL COMMENT '头像',
  `store_img` TEXT(65535) NULL COMMENT '店铺照片，多个用*分割',
  `store_name` VARCHAR(128) NULL COMMENT '店铺名称',
  `store_level` INT NULL DEFAULT 1 COMMENT '店铺等级，默认1表示普通店铺，2表示银牌店铺，3表示金牌店铺',
  `credit_level` INT NULL DEFAULT 1 COMMENT '信誉等级，默认1',
  `sale_number` INT NULL DEFAULT 0 COMMENT '销售量',
  `sale_money` DECIMAL(10,2) NULL DEFAULT 0.00 COMMENT '销售额，默认0.00',
  `user_name` VARCHAR(128) NULL COMMENT '联系人姓名',
  `phone` VARCHAR(11) NULL COMMENT '手机',
  `wx_name` VARCHAR(128) NULL COMMENT '微信账号',
  `province` VARCHAR(45) NULL COMMENT '省',
  `city` VARCHAR(45) NULL COMMENT '市',
  `county` VARCHAR(45) NULL COMMENT '区',
  `county_code` VARCHAR(45) NULL COMMENT '区代码',
  `address` TEXT(65535) NULL COMMENT '详细地址：批发市场',
  `address_number` VARCHAR(128) NULL COMMENT '档口编号',
  `trade_area_id` BIGINT(20) NULL COMMENT '商圈id',
  `sell_type` BIGINT(20) NOT NULL COMMENT '售卖货物类型',
  `get_min` INT NULL DEFAULT 1 COMMENT '拿货最小量，默认1',
  `pack_min` INT NULL DEFAULT 5 COMMENT '打包起批量，默认5件',
  `mix_number` INT NULL DEFAULT 0 COMMENT '混批件数，默认0',
  `is_mix` INT NULL DEFAULT 0 COMMENT '是否支持混批，默认0不支持，1表示支持',
  `is_change` INT NULL DEFAULT 0 COMMENT '是否支持换货，默认0表示不支持，1表示支持',
  `spread_code` VARCHAR(512) NULL COMMENT '推广代码',
  `sure_money` INT NULL DEFAULT 0 COMMENT '保证金是否足够，默认0不足，1表示正常',
  `qr_url` VARCHAR(512) NULL COMMENT '我的二维码图片地址',
  `shop_notice` VARCHAR(1024) NULL COMMENT '店铺公告',
  `shop_deposit` DECIMAL(10,2) NULL DEFAULT 0.00 COMMENT '店铺押金',
  `fans` INT NULL DEFAULT 0 COMMENT '粉丝数',
  `rebuy_rate` DECIMAL(10,2) NULL DEFAULT 100.00 COMMENT '复购率，默认100%',
  `comment_number` INT NULL DEFAULT 0 COMMENT '评论数，默认0',
  `praise_rate` DECIMAL(10,2) NULL DEFAULT 100.00 COMMENT '好评率，默认100%',
  `service_level` INT NULL DEFAULT 5 COMMENT '商家服务等级，默认5星',
  `quality_level` INT NULL DEFAULT 5 COMMENT '商品品质，默认5星',
  `car_level` INT NULL DEFAULT 5 COMMENT '物流等级，默认5星',
  `operate_time` DATE NULL COMMENT '最近操作时间',
  `month_new` INT NULL COMMENT '月上新数',
  `lng` DECIMAL(10,5) NULL COMMENT '经度',
  `lat` DECIMAL(10,5) NULL COMMENT '纬度',
  `open_gold` INT NULL DEFAULT 0 COMMENT '是否开启金币兑换，默认0表示不开启，1表示开启',
  `all_gold_rate` INT NULL DEFAULT 0 COMMENT '全局金币兑换比率',
  `is_top_display` INT NULL DEFAULT 0 COMMENT '是否有高级橱窗，默认0表示没有，1表示有',
  `display_type` INT NULL DEFAULT 1 COMMENT '店铺展示类型，默认1表示一行两列，2表示一行三列，3表示大图，4表示封面细节图',
  `use_recommend_time` INT NULL DEFAULT 0 COMMENT '自动推荐今日使用次数',
  `left_recommend_time` INT NULL DEFAULT 0 COMMENT '自动推荐今日剩余次数',
  `status` INT NULL DEFAULT 0 COMMENT '认证状态:默认0表示认证中，1表示认证成功，2表示认证失败',
  PRIMARY KEY (`id`),
  INDEX `fk_seller_info_user1_idx` (`user_id` ASC),
  INDEX `fk_seller_info_sort_type1_idx` (`sell_type` ASC),
  INDEX `fk_shop_info_trade_area1_idx` (`trade_area_id` ASC),
  CONSTRAINT `fk_seller_info_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seller_info_sort_type1`
    FOREIGN KEY (`sell_type`)
    REFERENCES `jgsc`.`sort_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shop_info_trade_area1`
    FOREIGN KEY (`trade_area_id`)
    REFERENCES `jgsc`.`trade_area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '卖家信息';


-- -----------------------------------------------------
-- Table `jgsc`.`bull_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`bull_info` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `user_id` BIGINT(20) NOT NULL COMMENT '买家id',
  `bull_type` INT NULL COMMENT '买家（采购商）类型，1表示网络品牌店，2表示品牌连锁',
  `user_name` VARCHAR(128) NULL COMMENT '姓名',
  `phone` VARCHAR(11) NULL COMMENT '手机',
  `telephone` VARCHAR(45) NULL COMMENT '固定电话',
  `company_name` VARCHAR(128) NULL DEFAULT 1 COMMENT '公司名称',
  `company_address` VARCHAR(256) NULL COMMENT '公司地址',
  `card_url_face` VARCHAR(512) NULL COMMENT '名片正面',
  `card_url_con` VARCHAR(512) NULL COMMENT '名片反面',
  `qualification_url_face` VARCHAR(512) NULL COMMENT '资质图片正面',
  `qualification_url_con` VARCHAR(512) NULL COMMENT '资质图片反面',
  `status` INT NULL DEFAULT 0 COMMENT '认证状态:默认0表示认证中，1表示认证成功，2表示认证失败',
  PRIMARY KEY (`id`),
  INDEX `fk_bull_info_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_bull_info_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '买家信息';


-- -----------------------------------------------------
-- Table `jgsc`.`consultant_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`consultant_comment` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `user_id` BIGINT(20) NOT NULL COMMENT '用户id',
  `consultant_id` BIGINT(20) NOT NULL COMMENT '顾问id',
  `ability_point` INT NULL DEFAULT 5 COMMENT '能力得分，默认5',
  `attitude_point` INT NULL DEFAULT 5 COMMENT '态度分,默认5',
  `comment` TEXT(65535) NULL COMMENT '评论',
  `status` INT NULL COMMENT '默认1表示正常，2表示异常',
  PRIMARY KEY (`id`),
  INDEX `fk_consultant_comment_user1_idx` (`user_id` ASC),
  INDEX `fk_consultant_comment_consultant1_idx` (`consultant_id` ASC),
  CONSTRAINT `fk_consultant_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consultant_comment_consultant1`
    FOREIGN KEY (`consultant_id`)
    REFERENCES `jgsc`.`consultant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '顾问评论';


-- -----------------------------------------------------
-- Table `jgsc`.`colour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`colour` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `colour_name` VARCHAR(45) NULL COMMENT '颜色名',
  `colour_value` VARCHAR(45) NULL COMMENT '色值，16进制',
  `user_id` BIGINT(20) NULL COMMENT '用户id，存在表示此用户自己颜色，不存在则表示系统颜色',
  `status` INT NULL DEFAULT 1 COMMENT '默认1表示正常，2表示异常',
  PRIMARY KEY (`id`),
  INDEX `fk_colour_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_colour_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '颜色表';


-- -----------------------------------------------------
-- Table `jgsc`.`size`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`size` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `size_name` VARCHAR(45) NULL COMMENT '尺寸名字',
  `user_id` BIGINT(20) NULL COMMENT '用户id，存在表示此用户自己颜色，不存在则表示系统颜色',
  `status` INT NULL DEFAULT 1 COMMENT '默认1表示正常，2表示异常',
  PRIMARY KEY (`id`),
  INDEX `fk_colour_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_colour_user10`
    FOREIGN KEY (`user_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '尺寸表';


-- -----------------------------------------------------
-- Table `jgsc`.`goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`goods` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `shop_id` BIGINT(20) NOT NULL COMMENT '商家id',
  `cover_url` VARCHAR(512) NULL COMMENT '封面',
  `goods_url` TEXT(65535) NULL COMMENT '详细图',
  `goods_title` VARCHAR(512) NULL COMMENT '商品标题',
  `goods_simple` TEXT(65535) NULL COMMENT '商品简介',
  `trade_price` DECIMAL(10,2) NULL DEFAULT 0.00 COMMENT '批发价,默认0.00',
  `trade_number` INT NULL DEFAULT 1 COMMENT '批发件数,默认1件',
  `get_price` DECIMAL(10,2) NULL DEFAULT 0.00 COMMENT '拿货价，默认0.00',
  `get_number` INT NULL DEFAULT 1 COMMENT '拿货件数，默认1',
  `pack_price` DECIMAL(10,2) NULL DEFAULT 0.00 COMMENT '打包价',
  `pack_number` INT NULL DEFAULT 1 COMMENT '打包件数，默认1件',
  `weight` INT NULL DEFAULT 0 COMMENT '重量，默认0包邮',
  `is_index` INT NULL DEFAULT 0 COMMENT '是否推荐到首页，默认0',
  `is_member` INT NULL DEFAULT 0 COMMENT '是否会员查看',
  `format_care` INT NULL DEFAULT 0 COMMENT '是否版式保护，默认0不保护',
  `total` INT NULL DEFAULT 0 COMMENT '商品总库存',
  `sale_num` INT NULL DEFAULT 0 COMMENT '售卖件数',
  `left_num` INT NULL DEFAULT 0 COMMENT '剩余库存',
  `look_time` INT NULL DEFAULT 0 COMMENT '浏览次数',
  `goods_type` INT NULL DEFAULT 2 COMMENT '商品类型，1表示首页，默认2表示上新，3表示热卖，4表示会员，5表示尾货',
  `collect_num` INT NULL DEFAULT 0 COMMENT '被收藏数量，默认0',
  `gold_rate` INT NULL DEFAULT 0 COMMENT '金币比例，默认0表示不支持金币兑换，其他则表示金币比率',
  `status` INT NULL DEFAULT 0 COMMENT '商品状态，默认0表示未上架，1表示上架中，2表示下架，3表示已删除',
  PRIMARY KEY (`id`),
  INDEX `fk_goods_shop_info1_idx` (`shop_id` ASC),
  CONSTRAINT `fk_goods_shop_info1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `jgsc`.`shop_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '商品表';


-- -----------------------------------------------------
-- Table `jgsc`.`property_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`property_type` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `property_name` VARCHAR(128) NULL COMMENT '属性名',
  `one_type_id` BIGINT(20) NULL COMMENT '一级目录',
  `two_type_id` BIGINT(20) NULL COMMENT '二级目录（备用）',
  `status` INT NULL DEFAULT 1 COMMENT '默认1表示正常，2表示弃用',
  PRIMARY KEY (`id`))
COMMENT = '属性表';


-- -----------------------------------------------------
-- Table `jgsc`.`property_betweeen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`property_betweeen` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `property_type_id` BIGINT(20) NOT NULL COMMENT '属性id',
  `goods_id` BIGINT(20) NOT NULL COMMENT '商品id',
  `remark` VARCHAR(512) NULL COMMENT '备用字段',
  `status` INT NULL DEFAULT 1 COMMENT '默认1表示正常，2表示删除',
  PRIMARY KEY (`id`),
  INDEX `fk_property_betweeen_property_type1_idx` (`property_type_id` ASC),
  INDEX `fk_property_betweeen_goods1_idx` (`goods_id` ASC),
  CONSTRAINT `fk_property_betweeen_property_type1`
    FOREIGN KEY (`property_type_id`)
    REFERENCES `jgsc`.`property_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_property_betweeen_goods1`
    FOREIGN KEY (`goods_id`)
    REFERENCES `jgsc`.`goods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '属性-商品关系表';


-- -----------------------------------------------------
-- Table `jgsc`.`sort_betweeen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`sort_betweeen` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `sort_type_id` BIGINT(20) NOT NULL COMMENT '类别id',
  `goods_id` BIGINT(20) NOT NULL COMMENT '商品id',
  `remark` VARCHAR(512) NULL COMMENT '备用字段',
  `status` INT NULL DEFAULT 1 COMMENT '默认1表示正常，2表示删除',
  PRIMARY KEY (`id`),
  INDEX `fk_property_betweeen_goods1_idx` (`goods_id` ASC),
  INDEX `fk_sort_betweeen_sort_type1_idx` (`sort_type_id` ASC),
  CONSTRAINT `fk_property_betweeen_goods10`
    FOREIGN KEY (`goods_id`)
    REFERENCES `jgsc`.`goods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sort_betweeen_sort_type1`
    FOREIGN KEY (`sort_type_id`)
    REFERENCES `jgsc`.`sort_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '类别-商品关系表';


-- -----------------------------------------------------
-- Table `jgsc`.`want_buy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`want_buy` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `user_id` BIGINT(20) NOT NULL COMMENT '发布者id',
  `cover_url` VARCHAR(512) NULL COMMENT '封面',
  `goods_url` TEXT(65535) NULL COMMENT '详细图,多个用*分割',
  `trade_area_id` BIGINT(20) NOT NULL COMMENT '商圈id',
  `sort_type_id` BIGINT(20) NOT NULL COMMENT '商品类别',
  `qq` VARCHAR(45) NULL,
  `contact_name` VARCHAR(128) NULL COMMENT '联系人姓名',
  `goods_num` INT NULL COMMENT '需求数量',
  `address` VARCHAR(512) NULL COMMENT '需求地址',
  `goods_describe` TEXT(65535) NULL COMMENT '商品描述',
  `status` INT NULL DEFAULT 0 COMMENT '默认0表示未发布，1表示已发布，2表示下架',
  PRIMARY KEY (`id`),
  INDEX `fk_want_buy_user1_idx` (`user_id` ASC),
  INDEX `fk_want_buy_trade_area1_idx` (`trade_area_id` ASC),
  INDEX `fk_want_buy_sort_type1_idx` (`sort_type_id` ASC),
  CONSTRAINT `fk_want_buy_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_want_buy_trade_area1`
    FOREIGN KEY (`trade_area_id`)
    REFERENCES `jgsc`.`trade_area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_want_buy_sort_type1`
    FOREIGN KEY (`sort_type_id`)
    REFERENCES `jgsc`.`sort_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '求购表';


-- -----------------------------------------------------
-- Table `jgsc`.`colour_betweeen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`colour_betweeen` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `colour_id` BIGINT(20) NOT NULL,
  `goods_id` BIGINT(20) NULL COMMENT '商品id',
  `want_buy_id` BIGINT(20) NULL COMMENT '求购id',
  `remark` VARCHAR(512) NULL COMMENT '备用字段',
  `status` INT NULL DEFAULT 1 COMMENT '默认1表示正常，2表示删除',
  PRIMARY KEY (`id`),
  INDEX `fk_sort_betweeen_copy1_colour1_idx` (`colour_id` ASC),
  INDEX `fk_colour_betweeen_goods1_idx` (`goods_id` ASC),
  INDEX `fk_colour_betweeen_want_buy1_idx` (`want_buy_id` ASC),
  CONSTRAINT `fk_sort_betweeen_copy1_colour1`
    FOREIGN KEY (`colour_id`)
    REFERENCES `jgsc`.`colour` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_colour_betweeen_goods1`
    FOREIGN KEY (`goods_id`)
    REFERENCES `jgsc`.`goods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_colour_betweeen_want_buy1`
    FOREIGN KEY (`want_buy_id`)
    REFERENCES `jgsc`.`want_buy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '颜色-商品关系表';


-- -----------------------------------------------------
-- Table `jgsc`.`size_betweeen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`size_betweeen` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `size_id` BIGINT(20) NOT NULL COMMENT '尺寸id',
  `goods_id` BIGINT(20) NULL COMMENT '商品id',
  `want_buy_id` BIGINT(20) NULL,
  `remark` VARCHAR(512) NULL COMMENT '备用字段',
  `status` INT NULL DEFAULT 1 COMMENT '默认1表示正常，2表示删除',
  PRIMARY KEY (`id`),
  INDEX `fk_colour_betweeen_copy1_size1_idx` (`size_id` ASC),
  CONSTRAINT `fk_colour_betweeen_copy1_size1`
    FOREIGN KEY (`size_id`)
    REFERENCES `jgsc`.`size` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '尺寸-商品关系表';


-- -----------------------------------------------------
-- Table `jgsc`.`goods_stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`goods_stock` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `goods_id` BIGINT(20) NOT NULL COMMENT '商品id',
  `colour_id` BIGINT(20) NOT NULL COMMENT '颜色id',
  `size_id` BIGINT(20) NOT NULL COMMENT '尺寸id',
  `total` INT NULL DEFAULT 10000 COMMENT '商品总量，默认10000件',
  `sale_num` INT NULL DEFAULT 0 COMMENT '售卖件数',
  `left_num` INT NULL DEFAULT 0 COMMENT '剩余库存',
  `status` INT NULL DEFAULT 0 COMMENT '默认1表示正常，2表示下架',
  PRIMARY KEY (`id`),
  INDEX `fk_goods_stock_goods1_idx` (`goods_id` ASC),
  INDEX `fk_goods_stock_colour1_idx` (`colour_id` ASC),
  INDEX `fk_goods_stock_size1_idx` (`size_id` ASC),
  CONSTRAINT `fk_goods_stock_goods1`
    FOREIGN KEY (`goods_id`)
    REFERENCES `jgsc`.`goods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_goods_stock_colour1`
    FOREIGN KEY (`colour_id`)
    REFERENCES `jgsc`.`colour` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_goods_stock_size1`
    FOREIGN KEY (`size_id`)
    REFERENCES `jgsc`.`size` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '商品库存表';


-- -----------------------------------------------------
-- Table `jgsc`.`seller_regist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`seller_regist` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `user_id` BIGINT(20) NOT NULL COMMENT '卖家id',
  `seller_type` INT NULL COMMENT '卖家类型：1表示实体店，2表示工厂店，3表示网批店',
  `head_img` VARCHAR(512) NULL COMMENT '头像',
  `store_img` TEXT(65535) NULL COMMENT '店铺照片，多个用*分割',
  `store_name` VARCHAR(128) NULL COMMENT '店铺名称',
  `user_name` VARCHAR(128) NULL COMMENT '联系人姓名',
  `phone` VARCHAR(11) NULL COMMENT '手机',
  `province` VARCHAR(45) NULL COMMENT '省',
  `city` VARCHAR(45) NULL COMMENT '市',
  `county` VARCHAR(45) NULL COMMENT '区',
  `county_code` VARCHAR(45) NULL COMMENT '区代码',
  `address` TEXT(65535) NULL COMMENT '详细地址：批发市场',
  `address_number` VARCHAR(128) NULL COMMENT '档口编号',
  `sell_type` BIGINT(20) NOT NULL COMMENT '售卖货物类型',
  `get_min` INT NULL DEFAULT 1 COMMENT '拿货最小量，默认1',
  `pack_min` INT NULL DEFAULT 5 COMMENT '打包起批量，默认5件',
  `is_mix` INT NULL DEFAULT 0 COMMENT '是否支持混批，默认0不支持，1表示支持',
  `is_change` INT NULL DEFAULT 0 COMMENT '是否支持换货，默认0表示不支持，1表示支持',
  `spread_code` VARCHAR(512) NULL COMMENT '推广代码',
  `sure_money` INT NULL DEFAULT 0 COMMENT '保证金是否足够，默认0不足，1表示正常',
  `qr_url` VARCHAR(512) NULL COMMENT '我的二维码图片地址',
  `status` INT NULL DEFAULT 0 COMMENT '认证状态:默认0表示认证中，1表示认证成功，2表示认证失败',
  PRIMARY KEY (`id`),
  INDEX `fk_seller_info_user1_idx` (`user_id` ASC),
  INDEX `fk_seller_info_sort_type1_idx` (`sell_type` ASC),
  CONSTRAINT `fk_seller_info_user10`
    FOREIGN KEY (`user_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seller_info_sort_type10`
    FOREIGN KEY (`sell_type`)
    REFERENCES `jgsc`.`sort_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '卖家认证信息';


-- -----------------------------------------------------
-- Table `jgsc`.`my_foot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`my_foot` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `user_id` BIGINT(20) NOT NULL COMMENT '用户id',
  `goods_id` BIGINT(20) NOT NULL COMMENT '商品id',
  `status` INT NULL DEFAULT 1 COMMENT '足迹状态，默认1表示正常，2表示删除',
  PRIMARY KEY (`id`),
  INDEX `fk_my_foot_user1_idx` (`user_id` ASC),
  INDEX `fk_my_foot_goods1_idx` (`goods_id` ASC),
  CONSTRAINT `fk_my_foot_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_my_foot_goods1`
    FOREIGN KEY (`goods_id`)
    REFERENCES `jgsc`.`goods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '我的足迹';


-- -----------------------------------------------------
-- Table `jgsc`.`my_collection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`my_collection` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `user_id` BIGINT(20) NOT NULL COMMENT '用户id',
  `goods_id` BIGINT(20) NOT NULL COMMENT '商品id',
  `status` INT NULL DEFAULT 1 COMMENT '收藏状态，默认1表示正常，2表示删除',
  PRIMARY KEY (`id`),
  INDEX `fk_my_foot_user1_idx` (`user_id` ASC),
  INDEX `fk_my_foot_goods1_idx` (`goods_id` ASC),
  CONSTRAINT `fk_my_foot_user10`
    FOREIGN KEY (`user_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_my_foot_goods10`
    FOREIGN KEY (`goods_id`)
    REFERENCES `jgsc`.`goods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '我的收藏';


-- -----------------------------------------------------
-- Table `jgsc`.`focus_shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`focus_shop` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `shop_id` BIGINT(20) NOT NULL COMMENT '店铺id',
  `user_id` BIGINT(20) NOT NULL COMMENT '用户id',
  `status` INT NULL DEFAULT 1 COMMENT '状态默认1表示正常，2表示取消关注',
  PRIMARY KEY (`id`),
  INDEX `fk_focus_shop_shop_info1_idx` (`shop_id` ASC),
  INDEX `fk_focus_shop_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_focus_shop_shop_info1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `jgsc`.`shop_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_focus_shop_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '关注店铺';


-- -----------------------------------------------------
-- Table `jgsc`.`coupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`coupon` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `limit_money` DECIMAL(10,2) NULL DEFAULT 0.00 COMMENT '限制金额（满多少）',
  `save_money` DECIMAL(10,2) NULL DEFAULT 0.00 COMMENT '节约金额，默认0.00',
  `limit_time` DATE NULL COMMENT '限制使用时间',
  `get_limit` INT NULL DEFAULT 0 COMMENT '默认0表示不限制，其他则表示每人领取限制',
  `all_mount` INT NULL DEFAULT 0 COMMENT '优惠券总数',
  `use_mount` INT NULL DEFAULT 0 COMMENT '已使用的优惠券',
  `get_mount` INT NULL COMMENT '已领取未使用的优惠券',
  `coupon_type` INT NULL DEFAULT 1 COMMENT '默认1表示系统优惠券，2表示商家优惠券',
  `shop_id` BIGINT(20) NULL COMMENT '店铺id，优惠券为商家优惠券时必有',
  `type` INT NULL DEFAULT 1 COMMENT '默认1表示优惠券，2表示红包',
  `coupon_status` INT NULL COMMENT '优惠券状态，默认1表示正常，2表示暂停使用,3表示过期优惠券',
  PRIMARY KEY (`id`))
COMMENT = '优惠券,红包表';


-- -----------------------------------------------------
-- Table `jgsc`.`user_coupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`user_coupon` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `user_id` BIGINT(20) NOT NULL COMMENT '用户id',
  `coupon_id` BIGINT(20) NOT NULL COMMENT '优惠券id',
  `limit_money` DECIMAL(10,2) NULL COMMENT '限制金额',
  `save_money` DECIMAL(10,2) NULL COMMENT '节约金额',
  `type` INT NULL DEFAULT 1 COMMENT '默认1表示优惠券，2表示红包',
  `status` INT NULL DEFAULT 1 COMMENT '默认1表示正常，2表示已使用，3表示过期，4表示不能使用',
  PRIMARY KEY (`id`),
  INDEX `fk_user_coupon_coupon1_idx` (`coupon_id` ASC),
  INDEX `fk_user_coupon_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_coupon_coupon1`
    FOREIGN KEY (`coupon_id`)
    REFERENCES `jgsc`.`coupon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_coupon_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '用户优惠券列表';


-- -----------------------------------------------------
-- Table `jgsc`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`address` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `user_id` BIGINT(20) NULL COMMENT '用户id，如果是代客订单则可以不填',
  `user_name` VARCHAR(128) NULL COMMENT '用户名',
  `user_phone` VARCHAR(45) NULL COMMENT '用户手机',
  `province` VARCHAR(45) NULL COMMENT '省',
  `city` VARCHAR(45) NULL COMMENT '市',
  `county` VARCHAR(45) NULL COMMENT '区',
  `area_code` VARCHAR(45) NULL COMMENT '省代码，若无则用市代码',
  `county_code` VARCHAR(45) NULL COMMENT '区代码',
  `address` TEXT(65535) NULL COMMENT '详细地址',
  `level` INT NULL DEFAULT 0 COMMENT '默认0表示非默认地址，1表示默认地址',
  `status` INT NULL DEFAULT 1 COMMENT '地址状态，默认1表示正常状态，2表示弃用',
  PRIMARY KEY (`id`),
  INDEX `fk_address_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_address_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '地址信息';


-- -----------------------------------------------------
-- Table `jgsc`.`express`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`express` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `company_name` VARCHAR(128) NULL COMMENT '公司名',
  `express_number` VARCHAR(128) NULL COMMENT '快递单号',
  `express_img` TEXT(65535) NULL COMMENT '货运图片，可能多张，*分割',
  `type` INT NULL DEFAULT 1 COMMENT '默认1表示快递，2表示货运',
  `status` INT NULL DEFAULT 1 COMMENT '默认1表示已发货，2表示已收货，3表示其他',
  PRIMARY KEY (`id`))
COMMENT = '货物快递';


-- -----------------------------------------------------
-- Table `jgsc`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`order` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `order_number` VARCHAR(128) NOT NULL COMMENT '订单编号',
  `user_id` BIGINT(20) NULL COMMENT '用户id，如果是代客订单则不填',
  `goods_id` BIGINT(20) NOT NULL COMMENT '订单id',
  `shop_id` BIGINT(20) NOT NULL COMMENT '商家id',
  `goods_stock_id` BIGINT(20) NOT NULL COMMENT '颜色尺寸库存表id',
  `address_id` BIGINT(20) NOT NULL COMMENT '地址id',
  `price` DECIMAL(10,2) NULL COMMENT '单价',
  `goods_number` INT NULL COMMENT '商品数量',
  `order_money` DECIMAL(10,2) NULL DEFAULT 0.00 COMMENT '订单金额',
  `save_money` DECIMAL(10,2) NULL DEFAULT 0.00 COMMENT '优惠券优惠金额',
  `gold_num` INT NULL COMMENT '金币数量',
  `gold_money` DECIMAL(10,2) NULL COMMENT '金币抵扣金额',
  `pay_money` DECIMAL(10,2) NULL DEFAULT 0.00 COMMENT '支付金额',
  `freight_money` DECIMAL(10,2) NULL DEFAULT 0.00 COMMENT '运费，默认0.00表示包邮',
  `user_coupon_id` BIGINT(20) NULL COMMENT '优惠券红包id',
  `pay_type` INT NULL COMMENT '支付类型：默认1表示余额支付，2表示支付宝支付，3表示微信支付，4表示银联支付',
  `give_type` INT NULL DEFAULT 1 COMMENT '配送类型，默认1表示包邮，2表示快递，3表示物流到付',
  `order_type` INT NULL DEFAULT 1 COMMENT '默认1表示正常订单，2表示代客订单,3表示直播订单',
  `order_qrcode` VARCHAR(512) NULL COMMENT '订单二维码',
  `remark` TEXT(65535) NULL COMMENT '留言备注',
  `express_id` BIGINT(20) NULL COMMENT '快递费',
  `trade_status` INT NULL DEFAULT 0 COMMENT '货物状态，默认0表示未发货，1表示已发货,2表示已收货',
  `pay_time` DATE NULL COMMENT '付款时间',
  `send_time` DATE NULL COMMENT '发货时间',
  `take_time` DATE NULL COMMENT '收货时间',
  `status` INT NULL DEFAULT 0 COMMENT '订单状态，默认0表示未支付，1表示支付成功，2表示确认收货，3表示已评价，4表示客户删除，5表示商家删除，6表示买卖都删除，7表示订单取消，8表示订单申请退款中，9表示退款失败，10表示退款成功',
  PRIMARY KEY (`id`),
  INDEX `fk_order_goods1_idx` (`goods_id` ASC),
  INDEX `fk_order_user1_idx` (`user_id` ASC),
  INDEX `fk_order_shop_info1_idx` (`shop_id` ASC),
  INDEX `fk_order_goods_stock1_idx` (`goods_stock_id` ASC),
  INDEX `fk_order_user_coupon1_idx` (`user_coupon_id` ASC),
  INDEX `fk_order_address1_idx` (`address_id` ASC),
  INDEX `fk_order_express1_idx` (`express_id` ASC),
  CONSTRAINT `fk_order_goods1`
    FOREIGN KEY (`goods_id`)
    REFERENCES `jgsc`.`goods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_shop_info1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `jgsc`.`shop_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_goods_stock1`
    FOREIGN KEY (`goods_stock_id`)
    REFERENCES `jgsc`.`goods_stock` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_user_coupon1`
    FOREIGN KEY (`user_coupon_id`)
    REFERENCES `jgsc`.`user_coupon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `jgsc`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_express1`
    FOREIGN KEY (`express_id`)
    REFERENCES `jgsc`.`express` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '订单表';


-- -----------------------------------------------------
-- Table `jgsc`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`comment` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `goods_id` BIGINT(20) NULL COMMENT '商品id',
  `user_id` BIGINT(20) NOT NULL COMMENT '用户id',
  `order_id` BIGINT(20) NULL COMMENT '订单id',
  `comment_img` TEXT(65535) NULL COMMENT '评论图片,多张图片用*分割',
  `comment_content` TEXT(65535) NULL COMMENT '评论内容',
  `service_level` INT NULL DEFAULT 5 COMMENT '商家服务等级，默认5星',
  `quality_level` INT NULL DEFAULT 5 COMMENT '商品品质，默认5星',
  `car_level` INT NULL DEFAULT 5 COMMENT '物流等级，默认5星',
  `comment_level` INT NULL DEFAULT 1 COMMENT '评论等级，默认1是好评，2是中评，3是差评',
  `is_img` INT NULL DEFAULT 0 COMMENT '是否有图，默认0表示无图，1表示有图',
  `status` INT NULL DEFAULT 1 COMMENT '评论状态，默认1表示正常，2表示删除',
  PRIMARY KEY (`id`),
  INDEX `fk_comment_goods1_idx` (`goods_id` ASC),
  INDEX `fk_comment_user1_idx` (`user_id` ASC),
  INDEX `fk_comment_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_comment_goods1`
    FOREIGN KEY (`goods_id`)
    REFERENCES `jgsc`.`goods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `jgsc`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '评论表';


-- -----------------------------------------------------
-- Table `jgsc`.`zb_direct_seeding`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`zb_direct_seeding` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME(0) NULL COMMENT '创建时间',
  `upt_datetime` DATETIME(0) NULL COMMENT '更新时间',
  `seller_id` BIGINT(20) NULL COMMENT '直播者id(商家id)',
  `title` VARCHAR(256) NULL COMMENT '直播标题',
  `img_url` VARCHAR(256) NULL COMMENT '直播图片链接',
  `link_url` VARCHAR(512) NULL COMMENT '链接地址',
  `watch_amount` INT NULL DEFAULT 0 COMMENT '观看数',
  `thumbs_amount` INT NULL DEFAULT 0 COMMENT '点赞数',
  `start_time` DATE NULL COMMENT '开播时间',
  `end_time` DATE NULL COMMENT '结束时间',
  `trade_money` DECIMAL(10,2) NULL DEFAULT 0.00 COMMENT '交易金额',
  `password` VARCHAR(45) NULL COMMENT '私密直播密码',
  `pack_rate` DECIMAL(10,2) NULL COMMENT '直播商品打包优惠',
  `direct_type` INT NULL DEFAULT 1 COMMENT '默认1表示公共直播，2表示私密直播',
  `status` INT NULL DEFAULT 0 COMMENT '状态 默认0表示直播审批中，1表示直播预告,2表示直播中,3表示历史直播，4表示拒绝直播',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '直播表';


-- -----------------------------------------------------
-- Table `jgsc`.`goods_car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`goods_car` (
  `id` BIGINT(20) NOT NULL,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `user_id` BIGINT(20) NOT NULL COMMENT '用户id',
  `shop_id` BIGINT(20) NOT NULL COMMENT '商家id',
  `goods_id` BIGINT(20) NOT NULL COMMENT '商品id',
  `goods_stock_id` BIGINT(20) NOT NULL COMMENT '商品尺寸颜色库存表id',
  `price` DECIMAL(10,2) NULL COMMENT '单价',
  `goods_number` INT NULL COMMENT '商品数量',
  `zb_direct_seeding_id` BIGINT(20) NULL COMMENT '直播id',
  `pack_rate` DECIMAL(10,2) NULL COMMENT '打包优惠价',
  `goods_type` INT NULL DEFAULT 1 COMMENT '默认1表示普通订单，2表示直播订单',
  PRIMARY KEY (`id`),
  INDEX `fk_goods_car_goods1_idx` (`goods_id` ASC),
  INDEX `fk_goods_car_goods_stock1_idx` (`goods_stock_id` ASC),
  INDEX `fk_goods_car_user1_idx` (`user_id` ASC),
  INDEX `fk_goods_car_shop_info1_idx` (`shop_id` ASC),
  INDEX `fk_goods_car_zb_direct_seeding1_idx` (`zb_direct_seeding_id` ASC),
  CONSTRAINT `fk_goods_car_goods1`
    FOREIGN KEY (`goods_id`)
    REFERENCES `jgsc`.`goods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_goods_car_goods_stock1`
    FOREIGN KEY (`goods_stock_id`)
    REFERENCES `jgsc`.`goods_stock` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_goods_car_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_goods_car_shop_info1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `jgsc`.`shop_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_goods_car_zb_direct_seeding1`
    FOREIGN KEY (`zb_direct_seeding_id`)
    REFERENCES `jgsc`.`zb_direct_seeding` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '进货车';


-- -----------------------------------------------------
-- Table `jgsc`.`refund_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`refund_order` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `order_number` VARCHAR(128) NULL,
  `order_id` BIGINT(20) NOT NULL COMMENT '订单id',
  `goods_id` BIGINT(20) NOT NULL COMMENT '商品id',
  `user_id` BIGINT(20) NOT NULL COMMENT '用户id',
  `shop_id` BIGINT(20) NOT NULL COMMENT '商家id',
  `refund_type` INT NULL DEFAULT 1 COMMENT '退款类型，默认1表示退款退货，2表示仅退款',
  `refund_reason` TEXT(65535) NULL COMMENT '退款原因',
  `refund_money` DECIMAL(10,2) NULL DEFAULT 0.00 COMMENT '退款金额，默认0.00',
  `refund_remark` TEXT(65535) NULL COMMENT '退款备注',
  `status` INT NULL DEFAULT 1 COMMENT '退款状态，默认1表示退款中，2表示退款成功，3表示退款失败',
  PRIMARY KEY (`id`),
  INDEX `fk_refund_order_order1_idx` (`order_id` ASC),
  INDEX `fk_refund_order_goods1_idx` (`goods_id` ASC),
  INDEX `fk_refund_order_user1_idx` (`user_id` ASC),
  INDEX `fk_refund_order_shop_info1_idx` (`shop_id` ASC),
  CONSTRAINT `fk_refund_order_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `jgsc`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_refund_order_goods1`
    FOREIGN KEY (`goods_id`)
    REFERENCES `jgsc`.`goods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_refund_order_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_refund_order_shop_info1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `jgsc`.`shop_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '退款订单';


-- -----------------------------------------------------
-- Table `jgsc`.`admin_catalog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`admin_catalog` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME(0) NULL COMMENT '创建时间',
  `upt_datetime` DATETIME(0) NULL COMMENT '修改时间',
  `catalog_name` VARCHAR(255) NULL COMMENT '目录名字',
  `parent_id` BIGINT(20) NULL COMMENT '父目录，没有则为null',
  `url` VARCHAR(255) NULL COMMENT '页面url',
  `status` INT(11) NULL COMMENT '状态:默认1正常,2删除',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '目录表';


-- -----------------------------------------------------
-- Table `jgsc`.`zb_gift`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`zb_gift` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME(0) NULL COMMENT '创建时间',
  `upt_datetime` DATETIME(0) NULL COMMENT '更新时间',
  `zb_direct_seeding_id` BIGINT(20) NOT NULL COMMENT '直播id',
  `user_id` BIGINT(20) NOT NULL COMMENT '用户id',
  `seller_id` BIGINT(20) NOT NULL COMMENT '卖家id',
  `gold_num` INT NULL DEFAULT 1 COMMENT '金币数，默认1',
  `status` INT NULL DEFAULT 1 COMMENT '默认1表示打赏成功',
  PRIMARY KEY (`id`),
  INDEX `fk_zb_gift_zb_direct_seeding1_idx` (`zb_direct_seeding_id` ASC),
  INDEX `fk_zb_gift_user1_idx` (`user_id` ASC),
  INDEX `fk_zb_gift_user2_idx` (`seller_id` ASC),
  CONSTRAINT `fk_zb_gift_zb_direct_seeding1`
    FOREIGN KEY (`zb_direct_seeding_id`)
    REFERENCES `jgsc`.`zb_direct_seeding` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zb_gift_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zb_gift_user2`
    FOREIGN KEY (`seller_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '礼品表';


-- -----------------------------------------------------
-- Table `jgsc`.`admin_jurisdiction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`admin_jurisdiction` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME(0) NULL COMMENT '创建时间',
  `upt_datetime` DATETIME(0) NULL COMMENT '更新时间',
  `user_id` BIGINT(20) NOT NULL COMMENT '用户id',
  `catalog_id` BIGINT(20) NOT NULL COMMENT '权限id',
  `status` INT(11) NULL COMMENT '状态:默认1正常,2删除',
  PRIMARY KEY (`id`),
  INDEX `fk_admin_jurisdiction_admin_catalog1_idx` (`catalog_id` ASC),
  INDEX `fk_admin_jurisdiction_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_admin_jurisdiction_admin_catalog1`
    FOREIGN KEY (`catalog_id`)
    REFERENCES `jgsc`.`admin_catalog` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admin_jurisdiction_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5
COLLATE = big5_bin
COMMENT = '权限表';


-- -----------------------------------------------------
-- Table `jgsc`.`user_cash_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`user_cash_record` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME(0) NULL COMMENT '创建时间',
  `upt_datetime` DATETIME(0) NULL COMMENT '更新时间',
  `user_id` BIGINT(20) NULL COMMENT '用户id',
  `title` VARCHAR(100) NULL COMMENT '标题',
  `transaction_id` VARCHAR(255) NULL COMMENT '交易单号',
  `recoed_type` VARCHAR(50) NULL COMMENT '流水类型，1表示充值，2表示提现，3，乐捐4，购买商品(做成Enum)',
  `recharge_type` INT(11) NULL COMMENT '充值类型，1表示银联充值，2表示支付宝充值，3表示微信充值，4表示其他充值,5表示收入',
  `money` DECIMAL(10) NULL COMMENT '金额',
  `credit` INT(11) NULL COMMENT '支付积分',
  `cost_id` BIGINT(20) NULL COMMENT '消费的订单id',
  `user_cash_recordcol` VARCHAR(255) NULL COMMENT '订单编号，有可能多个，***分开',
  `pay_type` INT(11) NULL COMMENT '支付类型：1表示余额支付，2表示支付宝支付，3表示微信支付',
  `status` INT(2) NULL COMMENT '默认0表示不成功，1表示成功',
  `user_bank_type_bind_id` BIGINT(20) NULL COMMENT '提现银行卡id,0表示微信账号提现',
  `withdraw_status` INT(11) NULL COMMENT '提现状态:默认1申请中,2已打款,3失败',
  `remark` TEXT(0) NULL COMMENT '备注',
  `reason` TEXT(0) NULL COMMENT '提现失败原因',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用户消费记录表';


-- -----------------------------------------------------
-- Table `jgsc`.`zb_chat_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`zb_chat_record` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME(0) NULL COMMENT '创建时间',
  `upt_datetime` DATETIME(0) NULL,
  `user_id` BIGINT(20) NOT NULL,
  `user_name` VARCHAR(45) NULL COMMENT '用户昵称',
  `zb_direct_seeding_id` BIGINT(20) NOT NULL,
  `content` TEXT(65535) NULL COMMENT '聊天内容',
  `status` INT(11) NULL DEFAULT 1 COMMENT '状态，默认1表示正常',
  PRIMARY KEY (`id`),
  INDEX `fk_zb_chat_record_zb_direct_seeding1_idx` (`zb_direct_seeding_id` ASC),
  INDEX `fk_zb_chat_record_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_zb_chat_record_zb_direct_seeding1`
    FOREIGN KEY (`zb_direct_seeding_id`)
    REFERENCES `jgsc`.`zb_direct_seeding` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zb_chat_record_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '聊天记录表';


-- -----------------------------------------------------
-- Table `jgsc`.`zb_goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`zb_goods` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `zb_direct_seeding_id` BIGINT(20) NOT NULL COMMENT '直播id',
  `goods_id` BIGINT(20) NOT NULL COMMENT '商品id',
  PRIMARY KEY (`id`),
  INDEX `fk_zb_goods_zb_direct_seeding1_idx` (`zb_direct_seeding_id` ASC),
  INDEX `fk_zb_goods_goods1_idx` (`goods_id` ASC),
  CONSTRAINT `fk_zb_goods_zb_direct_seeding1`
    FOREIGN KEY (`zb_direct_seeding_id`)
    REFERENCES `jgsc`.`zb_direct_seeding` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zb_goods_goods1`
    FOREIGN KEY (`goods_id`)
    REFERENCES `jgsc`.`goods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '直播商品';


-- -----------------------------------------------------
-- Table `jgsc`.`chat_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`chat_record` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `user_id` BIGINT(20) NOT NULL COMMENT '用户id',
  `user_uuid` VARCHAR(32) NULL,
  `seller_id` BIGINT(20) NOT NULL,
  `seller_uuid` VARCHAR(32) NULL,
  `content` TEXT(65535) NULL,
  `chat_type` INT NULL DEFAULT 1 COMMENT '默认1表示文本聊天，2表示图片聊天，3表示商品链接',
  `type` INT NULL DEFAULT 1 COMMENT '默认1表示商家用户聊天，2表示客服用户聊天',
  `status` INT NULL DEFAULT 1 COMMENT '默认1表示正常',
  PRIMARY KEY (`id`),
  INDEX `fk_chat_record_user1_idx` (`user_id` ASC),
  INDEX `fk_chat_record_user2_idx` (`seller_id` ASC),
  CONSTRAINT `fk_chat_record_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chat_record_user2`
    FOREIGN KEY (`seller_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '聊天记录';


-- -----------------------------------------------------
-- Table `jgsc`.`blacklist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`blacklist` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `shop_id` BIGINT(20) NOT NULL COMMENT '店铺id',
  `user_id` BIGINT(20) NOT NULL COMMENT '用户id',
  `status` INT NULL DEFAULT 1 COMMENT '默认1表示拉黑，2表示取消拉黑',
  PRIMARY KEY (`id`),
  INDEX `fk_blacklist_shop_info1_idx` (`shop_id` ASC),
  INDEX `fk_blacklist_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_blacklist_shop_info1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `jgsc`.`shop_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_blacklist_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '黑名单';


-- -----------------------------------------------------
-- Table `jgsc`.`report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`report` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `shop_id` BIGINT(20) NOT NULL COMMENT '店铺id',
  `user_id` BIGINT(20) NOT NULL COMMENT '用户id',
  `report_type` INT NULL COMMENT '举报类型，1表示大量盗图，2表示价格虚高，3表示无实体店，4表示私下交易，5表示其他',
  `report_img` TEXT(65535) NULL COMMENT '举报图片,多个用*分割',
  `report_content` TEXT(65535) NULL COMMENT '举报内容',
  `status` INT NULL DEFAULT 1 COMMENT '默认1表示正常举报',
  PRIMARY KEY (`id`),
  INDEX `fk_blacklist_shop_info1_idx` (`shop_id` ASC),
  INDEX `fk_blacklist_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_blacklist_shop_info10`
    FOREIGN KEY (`shop_id`)
    REFERENCES `jgsc`.`shop_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_blacklist_user10`
    FOREIGN KEY (`user_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '举报';


-- -----------------------------------------------------
-- Table `jgsc`.`auto_recommend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`auto_recommend` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `seller_id` BIGINT(20) NOT NULL COMMENT '卖家id',
  `shop_id` BIGINT(20) NOT NULL COMMENT '店铺id',
  `goods_id` BIGINT(20) NOT NULL COMMENT '商品id',
  `start_time` VARCHAR(45) NULL COMMENT '开始时间 格式hh:mm',
  `end_time` VARCHAR(45) NULL COMMENT '结束时间 格式hh:mm',
  `status` INT NULL DEFAULT 1 COMMENT '默认1表示推荐中，2表推荐结束,3表示系统关闭推荐',
  PRIMARY KEY (`id`),
  INDEX `fk_auto_recommend_shop_info1_idx` (`shop_id` ASC),
  INDEX `fk_auto_recommend_goods1_idx` (`goods_id` ASC),
  INDEX `fk_auto_recommend_user1_idx` (`seller_id` ASC),
  CONSTRAINT `fk_auto_recommend_shop_info1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `jgsc`.`shop_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_auto_recommend_goods1`
    FOREIGN KEY (`goods_id`)
    REFERENCES `jgsc`.`goods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_auto_recommend_user1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '自动推荐';


-- -----------------------------------------------------
-- Table `jgsc`.`increment_service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`increment_service` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `title` VARCHAR(128) NULL COMMENT '标题',
  `price` DECIMAL(10,2) NULL COMMENT '橱窗价格',
  `gold_num` INT NULL COMMENT '金币所需数',
  `validity_time` INT NULL DEFAULT 0 COMMENT '有效时间',
  `recommend_time` INT NULL COMMENT '推荐次数,自动推荐才有，其他的没有',
  `type` INT NULL COMMENT '1表示首页橱窗，2表示自动推荐,3表示重启店铺，4表示购买上新数,5表示首页轮播图,6表示app启动图',
  `status` INT NULL DEFAULT 1 COMMENT '默认1表示正常，2表示过期',
  PRIMARY KEY (`id`))
COMMENT = '增值服务';


-- -----------------------------------------------------
-- Table `jgsc`.`service_between`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`service_between` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `increment_service_id` BIGINT(20) NOT NULL COMMENT '增值服务id',
  `seller_id` BIGINT(20) NOT NULL COMMENT '卖家id',
  `shop_id` BIGINT(20) NOT NULL COMMENT '店铺id',
  `gold_num` INT NULL DEFAULT 0 COMMENT '金币数量，默认0',
  `money` DECIMAL(10,2) NULL COMMENT '金额',
  `pay_type` INT NULL COMMENT '支付类型：默认1表示余额支付，2表示支付宝支付，3表示微信支付，4表示银联支付,5表示金币兑换',
  `pay_time` DATE NULL COMMENT '支付时间',
  `status` INT NULL DEFAULT 0 COMMENT '状态，默认0表示未支付，1表示支付成功',
  `valid_time` DATE NULL COMMENT '有效时间',
  PRIMARY KEY (`id`),
  INDEX `fk_service_between_increment_service1_idx` (`increment_service_id` ASC),
  INDEX `fk_service_between_shop_info1_idx` (`shop_id` ASC),
  INDEX `fk_service_between_user1_idx` (`seller_id` ASC),
  CONSTRAINT `fk_service_between_increment_service1`
    FOREIGN KEY (`increment_service_id`)
    REFERENCES `jgsc`.`increment_service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_between_shop_info1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `jgsc`.`shop_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_between_user1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '增值服务中间表';


-- -----------------------------------------------------
-- Table `jgsc`.`auction_ad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`auction_ad` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `limit_time` DATE NULL COMMENT '截至时间',
  `start_time` DATE NULL COMMENT '广告位开始时间',
  `end_time` DATE NULL COMMENT '广告位截至时间',
  `ad_num` INT NULL DEFAULT 10 COMMENT '广告位数量，默认10',
  `status` INT NULL DEFAULT 1 COMMENT '默认1表示竞拍中，2表示竞拍结束展示中，3表示竞拍结束展示结束',
  PRIMARY KEY (`id`))
COMMENT = '竞拍广告位';


-- -----------------------------------------------------
-- Table `jgsc`.`auction_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`auction_record` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `auction_ad_id` BIGINT(20) NOT NULL COMMENT '竞拍广告id',
  `seller_id` BIGINT(20) NOT NULL COMMENT '卖家id',
  `pay_time` DATE NULL COMMENT '支付时间',
  `money` DECIMAL(10,2) NULL COMMENT '竞拍金额',
  `pay_type` INT NULL COMMENT '支付类型：默认1表示余额支付，2表示支付宝支付，3表示微信支付，4表示银联支付',
  `status` INT NULL DEFAULT 0 COMMENT '默认0表示未支付，1表示竞拍中，2表示竞拍失败已退款，3表示竞拍成功',
  PRIMARY KEY (`id`),
  INDEX `fk_auction_record_auction_ad1_idx` (`auction_ad_id` ASC),
  INDEX `fk_auction_record_user1_idx` (`seller_id` ASC),
  CONSTRAINT `fk_auction_record_auction_ad1`
    FOREIGN KEY (`auction_ad_id`)
    REFERENCES `jgsc`.`auction_ad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_auction_record_user1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '竞拍记录';


-- -----------------------------------------------------
-- Table `jgsc`.`ad_display`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`ad_display` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `shop_id` BIGINT(20) NOT NULL COMMENT '店铺id',
  `start_time` DATE NULL COMMENT '广告位开始时间',
  `end_time` DATE NULL COMMENT '广告位截至时间',
  `status` INT NULL DEFAULT 0 COMMENT '默认0表示等待展示，1表示展示中，2表示展示结束',
  PRIMARY KEY (`id`),
  INDEX `fk_ad_display_shop_info1_idx` (`shop_id` ASC),
  CONSTRAINT `fk_ad_display_shop_info1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `jgsc`.`shop_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '广告展示表';


-- -----------------------------------------------------
-- Table `jgsc`.`rush_goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`rush_goods` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `goods_id` BIGINT(20) NOT NULL COMMENT '商品id',
  `seller_id` BIGINT(20) NOT NULL COMMENT '卖家id',
  `cheap_price` DECIMAL(10,2) NULL COMMENT '优惠价',
  `rush_time` DATE NULL COMMENT '直播时间',
  `type` INT NULL COMMENT '抢购类型',
  `status` INT NULL DEFAULT 0 COMMENT '默认0表示审核中，1表示报名成功，2表示报名失败',
  PRIMARY KEY (`id`),
  INDEX `fk_rush_goods_goods1_idx` (`goods_id` ASC),
  INDEX `fk_rush_goods_user1_idx` (`seller_id` ASC),
  CONSTRAINT `fk_rush_goods_goods1`
    FOREIGN KEY (`goods_id`)
    REFERENCES `jgsc`.`goods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rush_goods_user1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '限时抢购商品';


-- -----------------------------------------------------
-- Table `jgsc`.`sign_active`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`sign_active` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `user_id` BIGINT(20) NOT NULL,
  `goods_id` BIGINT(20) NOT NULL,
  `phone` VARCHAR(45) NULL COMMENT '电话',
  `type` INT NULL COMMENT '1表示新品，2表示平台推荐，3表示七天换货，4表示一件代发',
  `status` INT NULL DEFAULT 0 COMMENT '默认0表示申请中，1表示申请成功，2表示申请失败',
  PRIMARY KEY (`id`),
  INDEX `fk_sign_active_user1_idx` (`user_id` ASC),
  INDEX `fk_sign_active_goods1_idx` (`goods_id` ASC),
  CONSTRAINT `fk_sign_active_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sign_active_goods1`
    FOREIGN KEY (`goods_id`)
    REFERENCES `jgsc`.`goods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '报名活动';


-- -----------------------------------------------------
-- Table `jgsc`.`express_price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`express_price` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `shop_id` BIGINT(20) NOT NULL COMMENT '商家id',
  `area_name` VARCHAR(256) NULL COMMENT '地区名',
  `area_code` VARCHAR(45) NULL COMMENT '地区代码，先省代码，若无则市代码',
  `first_money` DECIMAL(10,2) NULL DEFAULT 5 COMMENT '首重金额',
  `continued_money` DECIMAL(10,2) NULL DEFAULT 2 COMMENT '续重金额',
  `type` INT NULL DEFAULT 1 COMMENT '默认1表示地区快递，2表示默认快递费（必有一条）',
  `status` INT NULL DEFAULT 1 COMMENT '默认1表示正常，2表示弃用',
  PRIMARY KEY (`id`),
  INDEX `fk_express_shop_info1_idx` (`shop_id` ASC),
  CONSTRAINT `fk_express_shop_info1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `jgsc`.`shop_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '快递费设置';


-- -----------------------------------------------------
-- Table `jgsc`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`brand` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `seller_id` BIGINT(20) NOT NULL COMMENT '卖家id',
  `shop_id` BIGINT(20) NOT NULL COMMENT '店铺id',
  `brand_name` VARCHAR(128) NULL COMMENT '品牌名',
  `brand_img` VARCHAR(512) NULL COMMENT '品牌图片',
  `status` INT NULL DEFAULT 0 COMMENT '默认0表示申请中，1表示展示中，2表示下架',
  PRIMARY KEY (`id`),
  INDEX `fk_brand_user1_idx` (`seller_id` ASC),
  INDEX `fk_brand_shop_info1_idx` (`shop_id` ASC),
  CONSTRAINT `fk_brand_user1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_brand_shop_info1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `jgsc`.`shop_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '品牌';


-- -----------------------------------------------------
-- Table `jgsc`.`bank_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`bank_type` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `bank_name` VARCHAR(128) NULL COMMENT '银行名',
  `type` INT NULL DEFAULT 1 COMMENT '类别，默认1表示储蓄卡，2表示信用卡',
  `status` INT NULL DEFAULT 1 COMMENT '默认1表示可用，2表示不可用',
  PRIMARY KEY (`id`))
COMMENT = '银行类别';


-- -----------------------------------------------------
-- Table `jgsc`.`user_bank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`user_bank` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `user_id` BIGINT(20) NOT NULL COMMENT '用户id',
  `user_name` VARCHAR(64) NULL COMMENT '用户名',
  `bank_number` VARCHAR(45) NULL COMMENT '银行卡号',
  `bank_type_id` BIGINT(20) NOT NULL COMMENT '银行卡类别',
  `phone` VARCHAR(45) NULL COMMENT '手机号',
  `address` VARCHAR(512) NULL COMMENT '开户行地址',
  `reason` VARCHAR(512) NULL COMMENT '失败原因',
  `status` INT NULL DEFAULT 1 COMMENT '默认1表示成功，2表示是吧',
  PRIMARY KEY (`id`),
  INDEX `fk_user_bank_bank_type1_idx` (`bank_type_id` ASC),
  INDEX `fk_user_bank_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_bank_bank_type1`
    FOREIGN KEY (`bank_type_id`)
    REFERENCES `jgsc`.`bank_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_bank_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '用户银行卡';


-- -----------------------------------------------------
-- Table `jgsc`.`cash_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`cash_record` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `user_id` BIGINT(20) NOT NULL COMMENT '用户id(商家id) 等于0表示系统收入',
  `title` VARCHAR(512) NULL COMMENT '标题',
  `transaction_id` VARCHAR(256) NULL COMMENT '交易单号',
  `merchant_id` VARCHAR(256) NULL COMMENT '商家单号',
  `recoed_type` INT NULL COMMENT '1表示收入（充值、商家收入），2表示支出（消费、店铺押金）,3表示提现',
  `recharge_type` INT NULL COMMENT '充值类型，2表示支付宝支付，3表示微信支付，4表示银联支付',
  `money` DECIMAL(10,2) NULL COMMENT '金额',
  `gold` INT NULL COMMENT '金币',
  `order_ids` VARCHAR(256) NULL COMMENT '订单id,有可能多个订单id，多个用*分割',
  `pay_type` INT NULL COMMENT '支付类型：默认1表示余额支付，2表示支付宝支付，3表示微信支付，4表示银联支付',
  `user_bank_id` BIGINT(20) NULL,
  `withdraw_status` INT NULL DEFAULT 1 COMMENT '默认1表示提现审核中，2表示提现成功，3表示提现失败',
  `remark` VARCHAR(512) NULL COMMENT '提现备注',
  `status` INT NULL DEFAULT 1 COMMENT '默认1表示记录有效，2表示记录无效',
  PRIMARY KEY (`id`),
  INDEX `fk_cash_record_user1_idx` (`user_id` ASC),
  INDEX `fk_cash_record_user_bank1_idx` (`user_bank_id` ASC),
  CONSTRAINT `fk_cash_record_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cash_record_user_bank1`
    FOREIGN KEY (`user_bank_id`)
    REFERENCES `jgsc`.`user_bank` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '现金流水表';


-- -----------------------------------------------------
-- Table `jgsc`.`gold_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`gold_record` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `user_id` BIGINT(20) NOT NULL COMMENT '用户id(商家id)  等于0表示系统收入',
  `title` VARCHAR(512) NULL COMMENT '标题',
  `recoed_type` INT NULL COMMENT '1表示收入，2表示消费，3表示兑换增值服务',
  `gold` INT NULL COMMENT '金币',
  `auction_record_id` BIGINT(20) NOT NULL COMMENT '竞拍广告位记录',
  `increment_service_id` BIGINT(20) NOT NULL COMMENT '其他增值服务id',
  `valid_time` DATE NULL COMMENT '有效期',
  `status` INT NULL DEFAULT 1 COMMENT '默认1表示记录有效，2表示记录无效',
  PRIMARY KEY (`id`),
  INDEX `fk_cash_record_user1_idx` (`user_id` ASC),
  INDEX `fk_gold_record_increment_service1_idx` (`increment_service_id` ASC),
  INDEX `fk_gold_record_auction_record1_idx` (`auction_record_id` ASC),
  CONSTRAINT `fk_cash_record_user10`
    FOREIGN KEY (`user_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gold_record_increment_service1`
    FOREIGN KEY (`increment_service_id`)
    REFERENCES `jgsc`.`increment_service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gold_record_auction_record1`
    FOREIGN KEY (`auction_record_id`)
    REFERENCES `jgsc`.`auction_record` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '现金流水表';


-- -----------------------------------------------------
-- Table `jgsc`.`user_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`user_account` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `user_id` BIGINT(20) NOT NULL,
  `balance_money` DECIMAL(10,2) NULL COMMENT '可用余额',
  `block_money` DECIMAL(10,2) NULL COMMENT '冻结金额',
  `all_gold` INT NULL COMMENT '可用金币',
  `block_gold` INT NULL COMMENT '冻结金币',
  `status` INT NULL DEFAULT 1 COMMENT '默认1表示正常，2表示过期',
  PRIMARY KEY (`id`),
  INDEX `fk_user_account_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_account_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '用户账户表';


-- -----------------------------------------------------
-- Table `jgsc`.`help_center`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`help_center` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `title` VARCHAR(512) NULL,
  `content` TEXT(65535) NULL,
  `watch_time` INT NULL DEFAULT 0 COMMENT '观看数',
  `comment_num` INT NULL DEFAULT 0 COMMENT '评论数',
  `praise_num` INT NULL DEFAULT 0 COMMENT '点赞数，默认0',
  `type` INT NULL COMMENT '类型，1表示帮助中心',
  `status` INT NULL DEFAULT 1 COMMENT '1表示正常',
  PRIMARY KEY (`id`))
COMMENT = '帮助中心';


-- -----------------------------------------------------
-- Table `jgsc`.`help_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`help_comment` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `help_center_id` BIGINT(20) NOT NULL COMMENT '帮助中心id',
  `help_comment_id` BIGINT(20) NULL COMMENT '评论id，表示评论的评论',
  `user_id` BIGINT(20) NOT NULL,
  `content` TEXT(65535) NULL COMMENT '评论内容',
  `status` INT NULL DEFAULT 1 COMMENT '默认1表示正常，2表示违规删除',
  PRIMARY KEY (`id`),
  INDEX `fk_help_comment_help_center1_idx` (`help_center_id` ASC),
  INDEX `fk_help_comment_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_help_comment_help_center1`
    FOREIGN KEY (`help_center_id`)
    REFERENCES `jgsc`.`help_center` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_help_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '帮助中心评论表';


-- -----------------------------------------------------
-- Table `jgsc`.`source_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`source_type` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `source_name` VARCHAR(128) NULL,
  `type` INT NULL COMMENT '1表示自主访问，2表示站内付费，3表示付费流量',
  `status` INT NULL DEFAULT 1 COMMENT '默认1表示正常',
  PRIMARY KEY (`id`))
COMMENT = '来源类型';


-- -----------------------------------------------------
-- Table `jgsc`.`visit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`visit` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `user_id` BIGINT(20) NOT NULL COMMENT '用户id',
  `source_type_id` BIGINT(20) NOT NULL COMMENT '访问类型',
  PRIMARY KEY (`id`),
  INDEX `fk_visit_source_type1_idx` (`source_type_id` ASC),
  INDEX `fk_visit_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_visit_source_type1`
    FOREIGN KEY (`source_type_id`)
    REFERENCES `jgsc`.`source_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_visit_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '访问记录表';


-- -----------------------------------------------------
-- Table `jgsc`.`day_shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`day_shop` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `shop_id` BIGINT(20) NOT NULL COMMENT '商家id',
  `user_id` BIGINT(20) NOT NULL COMMENT '用户id',
  `vistor_num` INT NULL DEFAULT 0 COMMENT '访客数量',
  `watch_num` INT NULL DEFAULT 0 COMMENT '浏览量',
  `trade_money` DECIMAL(10,2) NULL DEFAULT 0.00 COMMENT '交易金额',
  `trade_rate` DECIMAL(10,2) NULL DEFAULT 0.00 COMMENT '转化率',
  `pay_num` INT NULL DEFAULT 0 COMMENT '支付买家次数',
  `order_num` INT NULL DEFAULT 0 COMMENT '订单量',
  `status` INT NULL DEFAULT 1 COMMENT '默认1表示正常',
  PRIMARY KEY (`id`),
  INDEX `fk_day_shop_shop_info1_idx` (`shop_id` ASC),
  INDEX `fk_day_shop_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_day_shop_shop_info1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `jgsc`.`shop_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_day_shop_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '每日店铺分析';


-- -----------------------------------------------------
-- Table `jgsc`.`each_picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`each_picture` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `img_url` VARCHAR(512) NULL COMMENT '图片地址',
  `link_url` VARCHAR(512) NULL COMMENT '链接地址',
  `content` TEXT(65535) NULL COMMENT '内容',
  `start_time` DATE NULL COMMENT '开始时间',
  `end_time` DATE NULL COMMENT '结束时间',
  `type` INT NULL COMMENT '类型',
  `status` INT NULL DEFAULT 0 COMMENT '默认0表示未发布，1表示发布中，2表示下架',
  PRIMARY KEY (`id`))
COMMENT = '广告轮播表';


-- -----------------------------------------------------
-- Table `jgsc`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`message` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `title` VARCHAR(512) NULL COMMENT '标题',
  `content` TEXT(65535) NULL COMMENT '详细内容',
  `type` INT NULL DEFAULT 1 COMMENT '默认1表示系统消息',
  `status` INT NULL DEFAULT 1 COMMENT '默认1表示正常，2表示下架',
  PRIMARY KEY (`id`))
COMMENT = '消息表';


-- -----------------------------------------------------
-- Table `jgsc`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`customer` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `user_id` BIGINT(20) NOT NULL COMMENT '客服id',
  `type` INT NULL COMMENT '客服类型，1表示VIP实名认证，2表示退换货，3表示进货咨询，4表示开店咨询，5表示资金提现，6表示店铺运营，7表示家港挑款，8表示软件崩溃',
  `status` INT NULL DEFAULT 1 COMMENT '默认1表示正常',
  PRIMARY KEY (`id`),
  INDEX `fk_customer_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_customer_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '客服表';


-- -----------------------------------------------------
-- Table `jgsc`.`tip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`tip` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `zb_direct_seeding_id` BIGINT(20) NULL COMMENT '直播id',
  `user_id` BIGINT(20) NOT NULL COMMENT '提醒人id',
  `rush_goods_id` BIGINT(20) NULL COMMENT '类型等于1表示直播提醒，2表示抢购提醒',
  `tip_time` DATE NULL COMMENT '提醒时间',
  `type` INT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_zb_tip_zb_direct_seeding1_idx` (`zb_direct_seeding_id` ASC),
  INDEX `fk_zb_tip_user1_idx` (`user_id` ASC),
  INDEX `fk_tip_rush_goods1_idx` (`rush_goods_id` ASC),
  CONSTRAINT `fk_zb_tip_zb_direct_seeding1`
    FOREIGN KEY (`zb_direct_seeding_id`)
    REFERENCES `jgsc`.`zb_direct_seeding` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zb_tip_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jgsc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tip_rush_goods1`
    FOREIGN KEY (`rush_goods_id`)
    REFERENCES `jgsc`.`rush_goods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '直播提醒表-抢购提醒';


-- -----------------------------------------------------
-- Table `jgsc`.`poop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jgsc`.`poop` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_datetime` DATETIME NULL,
  `upt_datetime` DATETIME NULL,
  `goods_id` BIGINT(20) NOT NULL COMMENT '商品id',
  `new_trade_price` DECIMAL(10,2) NULL DEFAULT 0.00 COMMENT '批发价,默认0.00',
  `new_get_price` DECIMAL(10,2) NULL DEFAULT 0.00 COMMENT '拿货价，默认0.00',
  `new_pack_price` DECIMAL(10,2) NULL DEFAULT 0.00 COMMENT '打包价',
  `status` INT NULL DEFAULT 1 COMMENT '默认1表示上架，2表示下降',
  PRIMARY KEY (`id`),
  INDEX `fk_poop_goods1_idx` (`goods_id` ASC),
  CONSTRAINT `fk_poop_goods1`
    FOREIGN KEY (`goods_id`)
    REFERENCES `jgsc`.`goods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '尾货表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
